################################################################################
# SNAKEMAKE SETUP
################################################################################
import glob
import os
def choose_prscs_input(wc):
    pattern = f"data/{wc.dataset}*.tsv.gz"
    candidates = glob.glob(pattern)
    if not candidates:
        raise ValueError(f"No file found matching {pattern}")
    if len(candidates) > 1:
        print(f"Warning: multiple matches for {wc.dataset}, using first: {candidates}")
    chosen = candidates[0]
    print(f"Using summary‐stats file for dataset {wc.dataset}: {chosen}")
    return chosen

from snakemake.utils import min_version
min_version("8.0")


#configfile: 'config/config_aadrita_2.yaml'
# Extract dataset names dynamically
DATASETS = list(config["summary_statistics"].keys()) 

#print("Loaded datasets:", DATASETS)


# Debugging: Print entire summary_statistics structure
import json
#print("Full summary_statistics config:", json.dumps(config["summary_statistics"], indent=4))

COHORTS = list(config["cohort"].keys())
#print("Loaded cohort:", COHORTS)
CHROMS  = config["PRScs-auto"]["chromosomes"]
#print("Loaded chromosomes:", CHROMS)
PHIS    = config["PRScs-auto"]["phi"]
#print("Loaded phis:", PHIS)


# Summary statistics
#POPULATION = list(config["summary_statistics"].keys())
#SAMPLE_SIZES = [str(details["sample_size"]) for details in config["summary_statistics"].values()]
SAMPLE_SIZES = lambda wc: config["summary_statistics"][wc.dataset]["sample_size"]
SS = [details["sst_file"] for details in config["summary_statistics"].values()]
SST = config["PRScs-auto"]["sst_file"]
#print("Loaded summary statistics:", SS)
LD_BUILD   = config["PRScs-auto"].get("ld_build", "GRCh37") # Default to GRCh37 if not specified
REF_LD = config["PRScs-auto"]["ref_ld"]
#print("Loaded reference LD:", REF_LD)
APPEND_COORDS = config["PRScs-auto"].get("append_coords_from_sumstats", False)
# APOE region configuration
APOE_CHR   = config["apoe"]["chrom"]
APOE_START = config["apoe"]["start"]
APOE_END   = config["apoe"]["end"]

shell.executable('/bin/bash')
#localrules: rule munge_variant
################################################################################
# FINAL RULE: Compile all resulting score files
################################################################################
rule all:
    input:
        expand(
            "results/{cohort}/{dataset}/{cohort}_phi{phi}_chrAll_noAPOE_pgsc_calc.txt",
            dataset=DATASETS,
            cohort=COHORTS,
            phi=PHIS
        ),
        expand(
            "results/{cohort}/{dataset}/{cohort}_phi{phi}_chrAll_noAPOE_scores.txt",
            dataset=DATASETS,
            cohort=COHORTS,
            phi=PHIS
        ),
        expand(
            "results/{cohort}/{dataset}/{cohort}_phi{phi}_chrAll.txt",
            dataset=DATASETS,
            cohort=COHORTS,
            phi=PHIS
        )#,
        #expand(
        #    "results/{cohort}_hm3_additive.raw",
        #    cohort=COHORTS if COHORTS else ["ADGC"]
        #)

################################################################################
# RULE 1: MUNGE SUMMARY STATISTICS
################################################################################
rule format_prscs:
    """
    Converts raw summary statistics into a format suitable for PRS-CS Auto.
    """
    input:
        raw = choose_prscs_input
    output:
        "work/{cohort}/formatted/{dataset}_formated_ss.txt"
    singularity:
        "docker://codewithrakshya/mungesumstats_docker"
    threads: 2
    resources:
        mem_mb=32000,
        time_min=1200
    script:
        "scripts/format_sumstats.R"

################################################################################
# RULE 2: MUNGE BIM / PVAR -> BED/BIM/FAM
################################################################################
rule munge_variant:
    """
    Build cohort_cpra2rsids.txt from .pvar or .bim depending on config[cohort][file_type]
    """
    input:
        variant = lambda wc: config["cohort"][wc.cohort]["genotype"] + (
            ".pvar" if config["cohort"][wc.cohort]["file_type"] == "pfile" else ".bim"
        )
    output:
        name_file = "resources/{cohort}/{cohort}_cpra2rsids.txt"
    params:
        geno_prefix = lambda wc: config["cohort"][wc.cohort]["genotype"]
    singularity: "docker://codewithrakshya/mungesumstats_docker"
    threads: 1
    resources:
        mem_mb=8000,   # 8 GB
        time_min=300
    script: "scripts/munge_variant.R"


################################################################################
# RULE 3: RUN PLINK2 TO UPDATE VARIANT IDS
################################################################################

rule run_plink:
    input:
        name_file = "resources/{cohort}/{cohort}_cpra2rsids.txt"
    output:
        bed = "resources/{cohort}/{cohort}.bed",
        bim = "resources/{cohort}/{cohort}.bim",
        fam = "resources/{cohort}/{cohort}.fam"
    params:
        plink_prefix = lambda wc: config["cohort"][wc.cohort]["genotype"],
        file_type    = lambda wc: config["cohort"][wc.cohort]["file_type"],
        plink_out    = lambda wc: f"resources/{wc.cohort}/{wc.cohort}"
    conda : "envs/plink.yaml"
    threads: 2
    resources:
        mem_mb=16000,  # 16GB RAM
        time_min=600   # 10 hours
    shell:
        """
        plink2 --{params.file_type} {params.plink_prefix} \
               --update-name {input.name_file} \
               --keep-allele-order \
               --make-bed \
               --out {params.plink_out}
        """

################################################################################
# RULE 3: PREPARE HAPMAP3 SNP LIST (OPTIONAL) Not Used
################################################################################
rule prepare_hm3:
    """
    Creates a list of HapMap3 SNPs (one ID per line) that will be used for filtering.
    """
    input:
        "resources/snpinfo_mult_1kg_hm3"
    output:
        "resources/w_hm3.snplist"
    shell:
        "cut -f1 {input} > {output}"

################################################################################
# RULE 4: FILTER GENOTYPE DATA TO HAPMAP3 SNPs
################################################################################
rule plink_filter:
    """
    Filters the genotype data (in PLINK format) to only HapMap3 SNPs.
    """
    input:
        bed = rules.run_plink.output.bed,
        bim = rules.run_plink.output.bim,
        fam = rules.run_plink.output.fam,
        hm3 = "resources/w_hm3.snplist"
    output:
        multiext("resources/hm3/{cohort}_hm3", ".bed", ".bim", ".fam")
    conda:
        "envs/plink.yaml"
    threads: 2
    resources:
        mem_mb=16000,  # 16GB RAM
        time_min=600   # 10 hours
    shell:
        """
        plink --bfile resources/{wildcards.cohort}/{wildcards.cohort} \
              --extract {input.hm3} \
              --make-bed \
              --out resources/hm3/{wildcards.cohort}_hm3
        """

################################################################################
# RULE 5: RUN PRS-CS AUTO (per chromosome, per cohort, per PHI) - Posterior effect size estimate → the estimated weight (beta coefficient) for A1 after PRS-CS’s Bayesian shrinkage. This is what you’d use to compute a polygenic score.
################################################################################

rule prscs_auto:
    """
    Runs PRS-CS Auto for each chromosome.
    """
    input:
        summary_stats = "work/{cohort}/formatted/{dataset}_formated_ss.txt",
        bfiles = lambda wc: [
            f"resources/hm3/{wc.cohort}_hm3.bed",
            f"resources/hm3/{wc.cohort}_hm3.bim",
            f"resources/hm3/{wc.cohort}_hm3.fam"]
    output:
        "results/{cohort}/{dataset}/{cohort}_pst_eff_a1_b0.5_phi{phi}_chr{chrom}.txt"
    params:
        #bim_prefix = f"resources/{COHORTS[0]}_hm3",
        bim_prefix = lambda wc: f"resources/hm3/{wc.cohort}_hm3",
        #phi_arg = lambda wildcards: f"--phi={PHIS}" if PHIS != 'auto' else '',
        phi_arg = lambda wc: f"--phi={wc.phi}" if wc.phi != 'auto' else '',
        chrom = "{chrom}",
        ss = SST,
        n = SAMPLE_SIZES,
        ref_ld = REF_LD

    conda:
        "envs/prscs.yaml"
    threads: 4
    resources:
        mem_mb=6400,
        time_min=1800
    shell:
        """
        python resources/PRScs/PRScs.py \
          --ref_dir={params.ref_ld}\
          --bim_prefix={params.bim_prefix} \
          --sst_file {params.ss} \
          --n_gwas={params.n} \
          --chrom={params.chrom} \
            {params.phi_arg} \
          --out_dir=results/{wildcards.cohort}/{wildcards.dataset}/{wildcards.cohort}
        """

################################################################################
# RULE 6: CONCATENATE CHR-SPECIFIC PRS WEIGHTS
################################################################################
rule concat_chrom_files:
    """
    Concatenates PRS-CS output from all chromosomes.
    """
    input:
        expand(
            "results/{{cohort}}/{{dataset}}/{{cohort}}_pst_eff_a1_b0.5_phi{{phi}}_chr{chrom}.txt",
            dataset=DATASETS,
            chrom=CHROMS
        )
    output:
        "results/{cohort}/{dataset}/{cohort}_phi{phi}_chrAll.txt"
    shell:
        "cat {input} > {output}"

################################################################################
# RULE 7: REMOVE APOE REGION (optional)
#add a check based on the build mentioned in the summary stats and also if else. 
#rerun the config files for aadrita and all the
################################################################################
rule rm_apoe:
    """
    If an `apoe:` section exists in config, removes that region;
    otherwise passes the file through unmodified.
    """
    input:
        rules.concat_chrom_files.output
    output:
        "results/{cohort}/{dataset}/{cohort}_phi{phi}_chrAll_noAPOE.txt"
    params:
        # Will be None if absent
        apoe_cfg = config.get("apoe", None)
    threads: 1
    resources:
        mem_mb=8000,  # 8GB RAM
        time_min=300  # 5 hours
    run:
        inp = input[0]
        out = output[0]
        if params.apoe_cfg:
            chr   = params.apoe_cfg["chrom"]
            start = params.apoe_cfg["start"]
            end   = params.apoe_cfg["end"]
            shell(
                r"""
                awk '$1 != {chr} || \
                    ($1 == {chr} && ($3 < {start} || $3 > {end}))' {inp} > {out}
                """.format(chr=chr, start=start, end=end, inp=inp, out=out)
            )
        else:
            shell("cp {inp} {out}".format(inp=inp, out=out))

################################################################################
# RULE 8: SCORE WITH PLINK
################################################################################
rule plink_score:
    """
    Uses PLINK to score individuals with the final PRS weights.
    """
    input:
        bfiles  = rules.plink_filter.output,
        weights = rules.rm_apoe.output
    output:
        "results/{cohort}/{dataset}/{cohort}_phi{phi}_chrAll_noAPOE_scores.txt"
    params:
        bfile = lambda wc: f"resources/hm3/{wc.cohort}_hm3"
    conda:
        "envs/plink.yaml"
    threads: 2
    resources:
        mem_mb=16000,  # 16GB RAM
        time_min=600   # 10 hours
    shell:
        """
        plink --bfile {params.bfile} \
              --score {input.weights} 2 4 6 sum \
              --out results/{wildcards.cohort}/{wildcards.dataset}/{wildcards.cohort}_{wildcards.phi}_chrAll_noAPOE_scores

        mv results/{wildcards.cohort}/{wildcards.dataset}/{wildcards.cohort}_{wildcards.phi}_chrAll_noAPOE_scores.profile {output}
        """


################################################################################
# RULE 9: COMPILE ALL SCORE FILES FOR PGSC_CALC
################################################################################
rule make_pgsc_calc_format:
    """
    Convert the final PRS-CS Auto output (after APOE removal) into a pgsc_calc-compatible file.
    """
    input:
        "results/{cohort}/{dataset}/{cohort}_phi{phi}_chrAll_noAPOE.txt"
    output:
        "results/{cohort}/{dataset}/{cohort}_phi{phi}_chrAll_noAPOE_pgsc_calc.txt"
    params:
        #genome_build = lambda wc: config["summary_statistics"][wc.dataset]["genome_build"]
        genome_build = LD_BUILD  # Use LD reference build for header
    threads: 1
    resources:
        mem_mb=8000,  # 8GB RAM
        time_min=300  # 5 hours
    shell:
        r"""
        awk -v build={params.genome_build} 'BEGIN {{
          print "#pgs_name={wildcards.cohort}_phi{wildcards.phi}_pst_eff_a1_b0.5_phiauto"
          print "#trait_reported={wildcards.dataset}"
          print "#genome_build=" build
          print "#pgs_id=custom"
          print "chr_name\tchr_position\teffect_allele\tother_allele\teffect_weight"
        }}
        {{
          print $1"\t"$3"\t"$4"\t"$5"\t"$6
        }}' {input} > {output}
        """

